const hardwareData = [
  {
    id: 1,
    deviceName: "Arduino Uno",
    category: "Microcontroller",
    totalQuantity: 10,
    borrowedQuantity: 4,
    pricePerUnit: 20,
    imageUrl: "/placeholder.svg?height=300&width=400",
    description: "Arduino Uno is a microcontroller board based on the ATmega328P.",
    specifications: {
      processor: "ATmega328P",
      clockSpeed: "16 MHz",
      digitalPins: 14,
      analogPins: 6,
    },
  },
  {
    id: 2,
    deviceName: "Raspberry Pi 4",
    category: "Single-board Computer",
    totalQuantity: 5,
    borrowedQuantity: 2,
    pricePerUnit: 35,
    imageUrl: "/placeholder.svg?height=300&width=400",
    description: "Raspberry Pi 4 Model B is the latest product in the popular Raspberry Pi range of computers.",
    specifications: {
      processor: "Broadcom BCM2711",
      ram: "2GB, 4GB, or 8GB",
      usb: "2 × USB 3.0 ports, 2 × USB 2.0 ports",
      wifi: "2.4 GHz and 5.0 GHz IEEE 802.11ac wireless",
    },
  },
  {
    id: 3,
    deviceName: "Breadboard",
    category: "Components",
    totalQuantity: 50,
    borrowedQuantity: 10,
    pricePerUnit: 5,
    imageUrl: "/placeholder.svg?height=300&width=400",
    description: "A breadboard is a solderless breadboard used for prototyping electronic circuits.",
    specifications: {
      size: "Various sizes available",
      material: "Plastic",
      connections: "Hundreds of connection points",
    },
  },
  {
    id: 4,
    deviceName: "DHT11 Temperature and Humidity Sensor",
    category: "Sensors",
    totalQuantity: 30,
    borrowedQuantity: 8,
    pricePerUnit: 3,
    imageUrl: "/placeholder.svg?height=300&width=400",
    description: "A DHT11 sensor measures temperature and humidity.",
    specifications: {
      temperatureRange: "0°C to 50°C",
      humidityRange: "20% to 90%",
      accuracy: "±2°C, ±5%RH",
    },
  },
  {
    id: 5,
    deviceName: "LED",
    category: "Components",
    totalQuantity: 100,
    borrowedQuantity: 20,
    pricePerUnit: 0.5,
    imageUrl: "/placeholder.svg?height=300&width=400",
    description: "A Light Emitting Diode (LED) is a semiconductor light source.",
    specifications: {
      colors: "Various colors available",
      voltage: "2-3V",
      current: "20mA",
    },
  },
  {
    id: 6,
    deviceName: "Resistor",
    category: "Components",
    totalQuantity: 200,
    borrowedQuantity: 40,
    pricePerUnit: 0.2,
    imageUrl: "/placeholder.svg?height=300&width=400",
    description:
      "A resistor is a passive two-terminal electrical component that implements electrical resistance as a circuit element.",
    specifications: {
      values: "Various values available",
      power: "0.25W",
    },
  },
  {
    id: 7,
    deviceName: "Capacitor",
    category: "Components",
    totalQuantity: 150,
    borrowedQuantity: 30,
    pricePerUnit: 0.3,
    imageUrl: "/placeholder.svg?height=300&width=400",
    description:
      "A capacitor is a passive two-terminal electrical component that stores electrical energy in an electric field.",
    specifications: {
      values: "Various values available",
      type: "Ceramic",
    },
  },
  {
    id: 8,
    deviceName: "Jumper Wires",
    category: "Components",
    totalQuantity: 1000,
    borrowedQuantity: 200,
    pricePerUnit: 0.1,
    imageUrl: "/placeholder.svg?height=300&width=400",
    description: "Jumper wires are used to connect components on a breadboard.",
    specifications: {
      length: "Various lengths available",
      gauge: "22 AWG",
    },
  },
  {
    id: 9,
    deviceName: "Potentiometer",
    category: "Components",
    totalQuantity: 50,
    borrowedQuantity: 10,
    pricePerUnit: 1,
    imageUrl: "/placeholder.svg?height=300&width=400",
    description:
      "A potentiometer is a three-terminal resistor with a sliding contact that forms an adjustable voltage divider.",
    specifications: {
      resistance: "10k ohms",
    },
  },
  {
    id: 10,
    deviceName: "Button",
    category: "Components",
    totalQuantity: 100,
    borrowedQuantity: 20,
    pricePerUnit: 0.5,
    imageUrl: "/placeholder.svg?height=300&width=400",
    description: "A button is used as an input device.",
    specifications: {
      type: "Tactile",
    },
  },
  {
    id: 11,
    deviceName: "Switch",
    category: "Components",
    totalQuantity: 50,
    borrowedQuantity: 10,
    pricePerUnit: 1,
    imageUrl: "/placeholder.svg?height=300&width=400",
    description: "A switch is used to turn circuits on and off.",
    specifications: {
      type: "Toggle",
    },
  },
  {
    id: 12,
    deviceName: "Ultrasonic Sensor",
    category: "Sensors",
    totalQuantity: 20,
    borrowedQuantity: 5,
    pricePerUnit: 5,
    imageUrl: "/placeholder.svg?height=300&width=400",
    description: "An ultrasonic sensor measures distance using sound waves.",
    specifications: {
      range: "2cm to 400cm",
    },
  },
  {
    id: 13,
    deviceName: "Servo Motor",
    category: "Actuators",
    totalQuantity: 10,
    borrowedQuantity: 2,
    pricePerUnit: 10,
    imageUrl: "/placeholder.svg?height=300&width=400",
    description:
      "A servo motor is a rotary actuator or linear actuator that allows for precise control of angular or linear position.",
    specifications: {
      type: "Standard",
    },
  },
  {
    id: 14,
    deviceName: "DC Motor",
    category: "Actuators",
    totalQuantity: 20,
    borrowedQuantity: 5,
    pricePerUnit: 5,
    imageUrl: "/placeholder.svg?height=300&width=400",
    description: "A DC motor is an electric motor that runs on direct current.",
    specifications: {
      voltage: "6V",
    },
  },
  {
    id: 15,
    deviceName: "Stepper Motor",
    category: "Actuators",
    totalQuantity: 10,
    borrowedQuantity: 2,
    pricePerUnit: 15,
    imageUrl: "/placeholder.svg?height=300&width=400",
    description:
      "A stepper motor is a brushless DC electric motor that divides a full rotation into a number of equal steps.",
    specifications: {
      steps: "200 steps per revolution",
    },
  },
  {
    id: 16,
    deviceName: "LCD Display",
    category: "Displays",
    totalQuantity: 5,
    borrowedQuantity: 1,
    pricePerUnit: 10,
    imageUrl: "/placeholder.svg?height=300&width=400",
    description: "A Liquid Crystal Display (LCD) is a flat-panel display that uses liquid crystals to produce images.",
    specifications: {
      size: "16x2 characters",
    },
  },
  {
    id: 17,
    deviceName: "OLED Display",
    category: "Displays",
    totalQuantity: 5,
    borrowedQuantity: 1,
    pricePerUnit: 15,
    imageUrl: "/placeholder.svg?height=300&width=400",
    description:
      "An Organic Light-Emitting Diode (OLED) display is a type of flat-panel display that uses organic compounds to produce light.",
    specifications: {
      size: "128x64 pixels",
    },
  },
  {
    id: 18,
    deviceName: "Power Supply",
    category: "Power",
    totalQuantity: 10,
    borrowedQuantity: 2,
    pricePerUnit: 5,
    imageUrl: "/placeholder.svg?height=300&width=400",
    description: "A power supply provides power to electronic devices.",
    specifications: {
      voltage: "5V",
      current: "2A",
    },
  },
  {
    id: 19,
    deviceName: "Battery",
    category: "Power",
    totalQuantity: 20,
    borrowedQuantity: 5,
    pricePerUnit: 2,
    imageUrl: "/placeholder.svg?height=300&width=400",
    description: "A battery is a device that converts chemical energy into electrical energy.",
    specifications: {
      type: "AA",
      voltage: "1.5V",
    },
  },
  {
    id: 20,
    deviceName: "Breadboard Jumper Wires",
    category: "Components",
    totalQuantity: 500,
    borrowedQuantity: 100,
    pricePerUnit: 0.2,
    imageUrl: "/placeholder.svg?height=300&width=400",
    description: "Assorted breadboard jumper wires for connecting components.",
    specifications: {
      colors: "Various colors",
      lengths: "Various lengths",
    },
  },
]

export default hardwareData

