const hardwareData = [
    {
      id: 1,
      deviceName: "Arduino Uno",
      category: "Microcontroller",
      totalQuantity: 10,
      borrowedQuantity: 4,
      pricePerUnit: 20,
    },
    {
      id: 2,
      deviceName: "Raspberry Pi 4",
      category: "Single-board Computer",
      totalQuantity: 5,
      borrowedQuantity: 2,
      pricePerUnit: 35,
    },
    {
      id: 3,
      deviceName: "ESP32",
      category: "Microcontroller",
      totalQuantity: 8,
      borrowedQuantity: 1,
      pricePerUnit: 15,
    },
    {
      id: 4,
      deviceName: "BeagleBone Black",
      category: "Single-board Computer",
      totalQuantity: 6,
      borrowedQuantity: 3,
      pricePerUnit: 45,
    },
    {
      id: 5,
      deviceName: "NodeMCU",
      category: "Microcontroller",
      totalQuantity: 12,
      borrowedQuantity: 5,
      pricePerUnit: 12,
    },
    {
      id: 6,
      deviceName: "Intel NUC",
      category: "Single-board Computer",
      totalQuantity: 4,
      borrowedQuantity: 1,
      pricePerUnit: 220,
    },
    {
      id: 7,
      deviceName: "Arduino Mega",
      category: "Microcontroller",
      totalQuantity: 15,
      borrowedQuantity: 7,
      pricePerUnit: 35,
    },
    {
      id: 8,
      deviceName: "Jetson Nano",
      category: "Single-board Computer",
      totalQuantity: 3,
      borrowedQuantity: 1,
      pricePerUnit: 100,
    },
    {
      id: 9,
      deviceName: "Particle Photon",
      category: "Microcontroller",
      totalQuantity: 10,
      borrowedQuantity: 2,
      pricePerUnit: 19,
    },
    {
      id: 10,
      deviceName: "Orange Pi Zero",
      category: "Single-board Computer",
      totalQuantity: 7,
      borrowedQuantity: 4,
      pricePerUnit: 25,
    },
    {
      id: 11,
      deviceName: "Tinker Board",
      category: "Single-board Computer",
      totalQuantity: 9,
      borrowedQuantity: 3,
      pricePerUnit: 50,
    },
    {
      id: 12,
      deviceName: "ESP8266",
      category: "Microcontroller",
      totalQuantity: 20,
      borrowedQuantity: 6,
      pricePerUnit: 8,
    },
    {
      id: 13,
      deviceName: "Adafruit Feather",
      category: "Microcontroller",
      totalQuantity: 10,
      borrowedQuantity: 2,
      pricePerUnit: 25,
    },
    {
      id: 14,
      deviceName: "Banana Pi M2",
      category: "Single-board Computer",
      totalQuantity: 5,
      borrowedQuantity: 2,
      pricePerUnit: 40,
    },
    {
      id: 15,
      deviceName: "Pine64",
      category: "Single-board Computer",
      totalQuantity: 8,
      borrowedQuantity: 4,
      pricePerUnit: 50,
    },
    {
      id: 16,
      deviceName: "Raspberry Pi Zero W",
      category: "Single-board Computer",
      totalQuantity: 12,
      borrowedQuantity: 3,
      pricePerUnit: 10,
    },
    {
      id: 17,
      deviceName: "Arduino Nano",
      category: "Microcontroller",
      totalQuantity: 20,
      borrowedQuantity: 6,
      pricePerUnit: 10,
    },
    {
      id: 18,
      deviceName: "STM32F4",
      category: "Microcontroller",
      totalQuantity: 10,
      borrowedQuantity: 4,
      pricePerUnit: 25,
    },
    {
      id: 19,
      deviceName: "Rock Pi 4",
      category: "Single-board Computer",
      totalQuantity: 5,
      borrowedQuantity: 1,
      pricePerUnit: 99,
    },
    {
      id: 20,
      deviceName: "Odroid XU4",
      category: "Single-board Computer",
      totalQuantity: 3,
      borrowedQuantity: 0,
      pricePerUnit: 80,
    },
];

export default hardwareData;
