const historyData = [
    {
      id: 1,
      category: "Arduino Board",
      deviceName: "Arduino Uno R3",
      borrowedQuantity: 2,
      borrowDate: "2023-11-15T10:00:00Z",
      returnDate: "2023-11-20T15:00:00Z",
      borrower: {
        id: 1,
        username: "admin",
        email: "admin@example.com",
        role: "admin",
        status: "Active",
      },
    },
    {
      id: 2,
      category: "Raspberry Pi",
      deviceName: "Raspberry Pi 4 Model B",
      borrowedQuantity: 1,
      borrowDate: "2023-12-01T09:00:00Z",
      returnDate: "2023-12-10T12:00:00Z",
      borrower: {
        id: 2,
        username: "user1",
        email: "user1@example.com",
        role: "user",
        status: "Inactive",
      },
    },
    {
      id: 3,
      category: "Microcontroller",
      deviceName: "ESP32",
      borrowedQuantity: 3,
      borrowDate: "2023-12-05T11:30:00Z",
      returnDate: null,
      borrower: {
        id: 3,
        username: "user2",
        email: "user2@example.com",
        role: "user",
        status: "Active",
      },
    },
    {
      id: 4,
      category: "Sensor Module",
      deviceName: "DHT11 Temperature and Humidity Sensor",
      borrowedQuantity: 5,
      borrowDate: "2023-11-25T14:15:00Z",
      returnDate: "2023-12-01T16:45:00Z",
      borrower: {
        id: 2,
        username: "user1",
        email: "user1@example.com",
        role: "user",
        status: "Inactive",
      },
    },
    {
      id: 5,
      category: "Development Kit",
      deviceName: "STM32 Discovery Kit",
      borrowedQuantity: 1,
      borrowDate: "2023-11-18T13:00:00Z",
      returnDate: "2023-11-25T10:00:00Z",
      borrower: {
        id: 1,
        username: "admin",
        email: "admin@example.com",
        role: "admin",
        status: "Active",
      },
    },
    {
      id: 6,
      category: "Camera Module",
      deviceName: "Raspberry Pi Camera Module V2",
      borrowedQuantity: 2,
      borrowDate: "2023-11-30T08:00:00Z",
      returnDate: null,
      borrower: {
        id: 3,
        username: "user2",
        email: "user2@example.com",
        role: "user",
        status: "Active",
      },
    },
  ];
  
  export default historyData;
  